version: '2.4'

name: servers
services:
  traefik:
    image: traefik:v2.10
    restart: always
    volumes:
      # So that Traefik can listen to the Docker events (read-only)
      - /run/user/1001/podman/podman.sock:/var/run/docker.sock:ro
      # TOML Configuration with global options
      - ${DATA_DIR}/traefik/traefik.toml:/traefik.toml
      # Configuration for the file provider (needed for host networking and default TLS Options)
      - ${DATA_DIR}/traefik/traefik-provider.toml:/traefik-provider.toml
      # LetsEncrypt ACME Configuration
      - ${DATA_DIR}/traefik/acme.json:/acme.json
      # Log File (optional)
      - ${DATA_DIR}/traefik/traefik.log:/traefik.log
      # Log File (optional)
      - ${DATA_DIR}/traefik/traefik-access.log:/traefik-access.log
    networks:
      - traefik
    ports:
      # The Web UI (enabled by --api.insecure=true in traefik.toml)
      - 8080:8080
      # The Available Ports (forward your router's incoming ports to the ports on the host)
      - 80:80
      - 443:443
    env_file: .env

  jellyfin:
    image: jellyfin/jellyfin
    group_add: # by id as these may not exist within the container. Needed to provide permissions to the VAAPI Devices
      - '107' #render
      - '44' #video
    tty: true
    networks:
      - traefik
    volumes:
      - ${DATA_DIR}/jellyfin/config:/config
      - ${DATA_DIR}/jellyfin/cache:/cache
      - /mnt/media:/media
    restart: unless-stopped
    devices:
      # VAAPI Devices
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    ports:
      - 8096:8096
    expose:
      - 8096
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.entrypoints=websecure
      - traefik.http.routers.jellyfin.rule=Host(`fin.sanare.dev`)

      # Middleware
      - traefik.http.routers.jellyfin.middlewares=jellyfin-mw
      - traefik.http.middlewares.jellyfin-mw.headers.customResponseHeaders.X-Robots-Tag=noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex
      - traefik.http.middlewares.jellyfin-mw.headers.STSSeconds=315360000
      #### The stsIncludeSubdomains is set to true, the includeSubDomains directive will be
      #### appended to the Strict-Transport-Security header.
      - traefik.http.middlewares.jellyfin-mw.headers.STSIncludeSubdomains=true
      #### Set stsPreload to true to have the preload flag appended to the Strict-Transport-Security header.
      - traefik.http.middlewares.jellyfin-mw.headers.STSPreload=true
      #### Set forceSTSHeader to true, to add the STS header even when the connection is HTTP.
      - traefik.http.middlewares.jellyfin-mw.headers.forceSTSHeader=true
      #### Set frameDeny to true to add the X-Frame-Options header with the value of DENY.
      - traefik.http.middlewares.jellyfin-mw.headers.frameDeny=true
      #### Set contentTypeNosniff to true to add the X-Content-Type-Options header with the value nosniff.
      - traefik.http.middlewares.jellyfin-mw.headers.contentTypeNosniff=true
      #### Set browserXssFilter to true to add the X-XSS-Protection header with the value 1; mode=block.
      - traefik.http.middlewares.jellyfin-mw.headers.customresponseheaders.X-XSS-PROTECTION=0
      #### The customFrameOptionsValue allows the X-Frame-Options header value to be set with a custom value. This
      #### overrides the FrameDeny option.
      - traefik.http.middlewares.jellyfin-mw.headers.customFrameOptionsValue='allow-from https://fin.sanare.dev'

  bookstack:
    image: lscr.io/linuxserver/bookstack:latest
    tty: true
    networks:
      - traefik
      - local
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Chicago
      APP_URL: https://docs.sanare.dev
      FILE__APP_KEY: /run/secrets/bookstack_app_key
      DB_HOST: bookstack_db
      DB_PORT: 3306
      DB_USERNAME: bookstack
      FILE__DB_PASSWORD: /run/secrets/bookstack_user
      DB_DATABASE: bookstack
    volumes:
      - ${DATA_DIR}/bookstack/config:/config
    ports:
      - 6875:6875
    expose:
      - 6875
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.bookstacks.entrypoints=websecure
      - traefik.http.routers.bookstacks.rule=Host(`docs.sanare.dev`)

      # Middleware
      - traefik.http.routers.bookstacks.middlewares=bookstacks-mw
      - traefik.http.middlewares.bookstacks-mw.headers.customResponseHeaders.X-Robots-Tag=noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex
      - traefik.http.middlewares.bookstacks-mw.headers.STSSeconds=315360000
      #### The stsIncludeSubdomains is set to true, the includeSubDomains directive will be
      #### appended to the Strict-Transport-Security header.
      - traefik.http.middlewares.bookstacks-mw.headers.STSIncludeSubdomains=true
      #### Set stsPreload to true to have the preload flag appended to the Strict-Transport-Security header.
      - traefik.http.middlewares.bookstacks-mw.headers.STSPreload=true
      #### Set forceSTSHeader to true, to add the STS header even when the connection is HTTP.
      - traefik.http.middlewares.bookstacks-mw.headers.forceSTSHeader=true
      #### Set frameDeny to true to add the X-Frame-Options header with the value of DENY.
      - traefik.http.middlewares.bookstacks-mw.headers.frameDeny=true
      #### Set contentTypeNosniff to true to add the X-Content-Type-Options header with the value nosniff.
      - traefik.http.middlewares.bookstacks-mw.headers.contentTypeNosniff=true
      #### Set browserXssFilter to true to add the X-XSS-Protection header with the value 1; mode=block.
      - traefik.http.middlewares.bookstacks-mw.headers.customresponseheaders.X-XSS-PROTECTION=0
      #### The customFrameOptionsValue allows the X-Frame-Options header value to be set with a custom value. This
      #### overrides the FrameDeny option.
      - traefik.http.middlewares.bookstacks-mw.headers.customFrameOptionsValue='allow-from https://docs.sanare.dev'
    secrets:
      - bookstack_user
      - bookstack_app_key

  bookstack_db:
    image: mariadb:latest
    tty: true
    networks:
      - local
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/bookstack_root
      MARIADB_PASSWORD_FILE: /run/secrets/bookstack_user
      MARIADB_USER: bookstack
      MARIADB_DATABASE: bookstack
    volumes:
      - ${DATA_DIR}/bookstack/data:/var/lib/mysql:Z
    ports:
      - 3306:3306
    secrets:
      - bookstack_user
      - bookstack_root

  minecraft:
    image: itzg/minecraft-server:java21-alpine
    tty: true
    stdin_open: true
    restart: unless-stopped
    networks:
      - test
    ports:
      - "25565:25565/tcp"
      - "25565:25565/udp"
      # Voice Chat Ports
      - "24454:24454/tcp"
      - "24454:24454/udp"
      # Bluemap Ports
      - "8100:8100/tcp"
      - "8100:8100/udp"
    expose:
      - "25565"
      - "24454"
      - "8100"
    environment:
      EULA: "TRUE"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      WHITELIST: "33ceed63-2539-4725-ad93-8c869aaf551e,fa8032ed-8b1f-4fad-a09c-0fe685332a46,4021e851-2b8c-4eca-a478-92f2ec11f067"
      ENFORCE_WHITELIST: "TRUE"
      ENFORCE_SECURE_PROFILE: "false"
      SYNC_CHUNK_WRITES: "false"
      USE_AIKAR_FLAGS: "TRUE"
      OPS: 33ceed63-2539-4725-ad93-8c869aaf551e,fa8032ed-8b1f-4fad-a09c-0fe685332a46
      OVERRIDE_OPS: "TRUE"
      DIFFICULTY: hard
      REMOVE_OLD_MODS: "TRUE"
      REMOVE_OLD_MODS_INCLUDE: "*.jar"
      REMOVE_OLD_MODS_DEPTH: 1
      REMOVE_OLD_MODS_EXCLUDE: ""
      SPAWN_PROTECTION: "0"
      MAX_TICK_TIME: 120000
      ENABLE_COMMAND_BLOCK: "TRUE"
      MEMORY: 8G
      TYPE: QUILT
      QUILT_LOADER_VERSION: 0.27.1
      VERSION: 1.21.4
      MODRINTH_PROJECTS: fabric-api:0.112.1+1.21.4,fabric-language-kotlin:1.13.0+kotlin.2.1.0,scalablelux:0.1.1+fabric.452731d,c2me-fabric:0.3.1+rc.1.0+1.21.4,lithium:t1FlWYl9,placeholder-api:2.5.1+1.21.3,simple-voice-chat:fabric-1.21.4-2.5.26,leaves-us-in-peace:1.7.2+MC1.21.2-1.21.4,cloth-config:17.0.142+fabric,x-backup:0.3.7+1.21.4,no-chat-reports:Fabric-1.21.4-v2.11.0,skinshuffle:2.6.0+1.21.4,chunk-debug:2.1.3+1.21.4,cape-command:0.2.1-1.21.4,datapack:skinful:1.1,datapack:info-tools:1.2.7
      # Move to carpet on modrinth once 1.21.4 is uploaded
      # https://github.com/gnembon/fabric-carpet/issues/2015
      MODS: https://github.com/gnembon/fabric-carpet/releases/download/1.4.161/fabric-carpet-1.21.4-1.4.161+v241203.jar
      VANILLATWEAKS_SHARECODE: d0RtSJ,JrE2PX
      MOTD: Vanilla
      ICON: https://raw.githubusercontent.com/rain-cafe-mc/servers/main/assets/icons/origins.png
      OVERRIDE_ICON: "TRUE"
    volumes:
      - ${DATA_DIR}/minecraft:/data

secrets:
   bookstack_app_key:
     file: ${PW_DIR}/bookstack_app_key
   bookstack_root:
     file: ${PW_DIR}/bookstack_root
   bookstack_user:
     file: ${PW_DIR}/bookstack_user

networks:
  traefik:
    external: false
  local:
    external: false
  test:
    driver: bridge
    external: false
